import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { uploadToS3 } from "../utils/s3";

export interface CustomsFormBooking {
  id: string;
}

export interface CustomsFormItem {
  name: string;
  description: string;
  weightLbs: number;
  declaredValueUsd: number;
  category: string;
  recipientName: string;
  recipientAddress: string;
  recipientCountry: string;
}

export interface CustomsFormPerson {
  firstName: string;
  lastName: string;
  postalAddress?: string | null;
  country?: string | null;
}

function categoryToCn22(category: string): string {
  if (category === "DOCUMENTS") return "gift";
  if (category === "ELECTRONICS" || category === "OTHER") return "other";
  return "other";
}

export async function generateCustomsForm(
  booking: CustomsFormBooking,
  item: CustomsFormItem,
  sender: CustomsFormPerson,
  traveler: CustomsFormPerson,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const qrPngBuffer = await QRCode.toBuffer(booking.id, { type: "png", width: 100, margin: 1 });

  doc.fontSize(16).text("LuggaLink", 50, 45);
  doc.fontSize(9).fillColor("gray").text("Peer-to-peer luggage logistics", 50, 65);
  doc.fillColor("black");
  doc.image(qrPngBuffer, doc.page.width - 150, 40, { width: 100, height: 100 });

  doc.moveDown(3);
  doc.fontSize(16).text("CUSTOMS DECLARATION (CN22/CN23)", 50, 150, { align: "center" });
  doc.moveDown();
  doc.fontSize(10).text(`Booking reference: ${booking.id}`, { align: "center" });
  doc.moveDown(1.5);

  const colX1 = 50;
  const colX2 = 310;
  const sectionY = doc.y;

  doc.fontSize(12).text("Sender", colX1, sectionY, { underline: true });
  doc.fontSize(10);
  doc.text(`${sender.firstName} ${sender.lastName}`, colX1, doc.y + 4);
  doc.text(sender.postalAddress ?? "N/A", colX1);
  doc.text(sender.country ?? "N/A", colX1);

  doc.fontSize(12).text("Recipient", colX2, sectionY, { underline: true });
  doc.fontSize(10);
  doc.text(item.recipientName, colX2, sectionY + 18);
  doc.text(item.recipientAddress, colX2);
  doc.text(item.recipientCountry, colX2);

  doc.moveDown(3);
  doc.x = colX1;
  doc.fontSize(12).text("Item details", { underline: true });
  doc.fontSize(10);
  doc.moveDown(0.5);

  const tableTop = doc.y;
  doc.text("Description", colX1, tableTop);
  doc.text("Qty", colX1 + 220, tableTop);
  doc.text("Weight (lbs)", colX1 + 270, tableTop);
  doc.text("Value (USD)", colX1 + 370, tableTop);
  doc.moveDown(0.5);
  doc.text(item.description || item.name, colX1, doc.y);
  doc.text("1", colX1 + 220, doc.y);
  doc.text(item.weightLbs.toFixed(2), colX1 + 270, doc.y);
  doc.text(`$${item.declaredValueUsd.toFixed(2)}`, colX1 + 370, doc.y);

  doc.moveDown(2);
  doc.x = colX1;
  doc.fontSize(10).text(`Category: ${categoryToCn22(item.category)}`, colX1);

  doc.moveDown(3);
  doc.fontSize(12).text("Carried by (traveler)", colX1, doc.y, { underline: true });
  doc.fontSize(10).text(`${traveler.firstName} ${traveler.lastName}`, colX1, doc.y + 4);

  doc.moveDown(3);
  doc.x = colX1;
  doc.fontSize(10).text("I certify that the particulars given in this declaration are correct.", colX1);
  doc.moveDown(2);
  doc.text("Sender signature: ____________________________", colX1);
  doc.moveDown(1);
  doc.text("Date: ____________________________", colX1);

  doc.fontSize(8).fillColor("gray").text(
    "Generated by LuggaLink",
    50,
    doc.page.height - 50,
    { align: "center", width: doc.page.width - 100 },
  );

  doc.end();

  return new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}

export async function generateAndUploadCustomsForm(
  booking: CustomsFormBooking,
  item: CustomsFormItem,
  sender: CustomsFormPerson,
  traveler: CustomsFormPerson,
): Promise<string> {
  const buffer = await generateCustomsForm(booking, item, sender, traveler);
  return uploadToS3({
    key: `customs-forms/${booking.id}.pdf`,
    body: buffer,
    contentType: "application/pdf",
  });
}
